[package]
name = "test1"
version = "0.1.0"
edition = "2024"

[dependencies]
doors_macros = { path = "../../doors_macros", version = "0.1.0", features = ["todo"]}

[build-dependencies]
doors_macros = { path = "../../doors_macros", version = "0.1.0" }
serde = {version = "1.0", features = ["serde_derive"] }
toml = "0.9.5"