[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
arraystring = {version = "0.3.0", default-features=false }
bitarray = "0.10.0"
doors_kernel_api = { path = "../doors_kernel_api", version = "0.1.0" }
doors_macros = { path = "../doors_macros", version = "0.1.0" }
doors_macros2 = { path = "../doors_macros2", version = "0.1.0" }
lazy_static = {version = "1.4.0", features = ["spin_no_std"] }
spin = "0.9.5"
volatile = "0.4.6"

[target.'cfg(target_arch = "x86")'.dependencies]
acpi = "4.1.1"
raw-cpuid = "11.0.1"
x86 = { version = "0.52.0" }
multiboot2 = "0.18.1"

[target.'cfg(target_arch = "x86_64")'.dependencies]
acpi = "4.1.1"
raw-cpuid = "11.0.1"
x86_64 = {git = "https://github.com/uglyoldbob/x86_64.git", version = "0.14.10", default-features=false, features = ["instructions"] }
multiboot2 = "0.18.1"

[profile.release]
debug = true