[build]
target = ["x86_64-unknown-none"]

[target.x86_64-unknown-none]
rustflags = ["-C", "relocation-model=pic", 
    "-C", "link-arg=-no-pie"]

[target.i386-unknown-none]
rustflags = ["-C", "relocation-model=pic", 
    "-C", "link-arg=-no-pie"]

[unstable]
build-std = ["core", "alloc"]