kernel_machine = "i386-unknown-none.json"
kernel_path = "i386-unknown-none"
disassembly = true

[kernel_config]
machine_name = "pc32"
acpi = true
gdbstub = true
mm_debug = false
test = false
network = false

[disk.unique.Cd]
kernel_path = "./build/iso/boot/kernel"

[disk.common]
output = "cd32.iso"
disk_label = "Doors OS"
config_files = [["grub2.lst", "./build/iso/boot/grub/grub.cfg"]]

[target.config]
net_devs = [0]
serial_ports = [0, 2]

[target.emulator.Qemu]
