kernel_machine = "i386-unknown-none.json"

[kernel_config]
machine_name = "pc32"
acpi = false
gdbstub = true
mm_debug = false
test = false
network = false

[disk.unique.Cd]
kernel_path = "./build/iso/boot/kernel"

[disk.common]
output = "cd32.iso"
disk_label = "Doors OS"
config_files = [[
    "./build/iso/boot/grub/grub.cfg",
    """
set timeout=1
set default=0 # Set the default menu entry
 
menuentry "Doors OS" {
   multiboot2 /boot/kernel testing
   boot
}""",
]]

[target.config]
net_devs = [0]

[target.emulator.Bochs]